version: '3.8'

services:
  psql_projeto_final:
    image: postgres:15-alpine
    env_file:
      - ./env.dev.psql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./psql_start:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app_projeto_final:
    depends_on:
      psql_projeto_final:
        condition: service_healthy
    build:
      dockerfile: build/Dockerfile.app
    ports:
      - "8080:5000"
    env_file:
      - ./env.dev.app
    networks:
      - rede_ada_projeto_final
    volumes:
      - ./src:/app

networks:
  rede_ada_projeto_final:
